#! /bin/bash

JAVA_INSTALL_VERSION_MAJOR='12'
JAVA_INSTALL_VERSION=1
MAGIC_B_NUM=12
JAVA_INSTALL_LINK_HASH=69cfe15208a647278a19ef0990eea691
JAVA_INSTALL_PATH=/usr/opt/java-${JAVA_INSTALL_VERSION_MAJOR}-${JAVA_INSTALL_VERSION}/
JDK_VERSION=${JAVA_INSTALL_VERSION_MAJOR}.0.${JAVA_INSTALL_VERSION}
DOWNLOAD_URL=http://download.oracle.com/otn-pub/java/jdk/${JDK_VERSION}+${MAGIC_B_NUM}/${JAVA_INSTALL_LINK_HASH}/jdk-${JDK_VERSION}_linux-x64_bin.tar.gz
JDK_FILE=/tmp/jdk-${JDK_VERSION}_linux-x64_bin.tar.gz
